
(require 'term)
(add-hook 'term-mode-hook
          (lambda ()
            (setq-local auto-revert-interval 1)
            (setq-local auto-revert-verbose nil)
            (setq-local truncate-lines nil)
            (setq-local auto-revert-set-timer nil)
            (auto-complete-mode 0)
            (auto-composition-mode 0)
            (auto-insert-mode 0)
            (auto-revert-mode 0)
            (company-mode 0)
            (font-lock-mode 1)
            (diff-auto-refine-mode 0)
            (diff-hl-mode 0)
            (diff-hl-flydiff-mode 0)
            (eldoc-mode 0)
            (electric-indent-local-mode 0)
            (hl-todo-mode nil)
            (file-name-shadow-mode 0)
            (yas-minor-mode 0)
            (paren-face-mode 0)
            (setq-local show-paren-mode nil)))


(define-key term-mode-map [C-left] 'previous-buffer)
(define-key term-mode-map [C-right] 'next-buffer)
(define-key term-raw-map [C-left] 'previous-buffer)
(define-key term-raw-map [C-right] 'next-buffer)
(define-key term-mode-map [?\M-x] (lookup-key (current-global-map) [M-x]))
(define-key term-raw-map [?\M-x] (lookup-key (current-global-map) [M-x]))
(define-key term-mode-map [C-y] 'yank)
(define-key term-raw-map [C-y] 'yank)
(define-key term-mode-map [C-w] (lookup-key (current-global-map) [C-w]))
(define-key term-raw-map [C-w] (lookup-key (current-global-map) [C-w]))

(provide 'mode-term)
