(require 'mode-ac)
(require 'mode-web-mode)
(require 'mode-js2)
(require 'mode-erlang)
(require 'mode-elixir)
(require 'mode-paren)
(require 'mode-paredit)
(require 'mode-paren-face)
(require 'mode-ido)
(require 'mode-slime)
(require 'mode-flyspell)
(require 'mode-flycheck)
(require 'mode-rainbow)
(require 'mode-diff-hl)
(require 'mode-iedit)
(require 'mode-magit)
(require 'mode-makefile)
;; (require 'mode-pdf-tools)
(require 'mode-prog-mode)
(require 'mode-isearch)
(require 'mode-dired)
(require 'mode-log)

(provide 'settings-modes)
